In [1]:
import pickle
import os, sys
import numpy as np
import pandas as pd
from pathlib import Path
from time import process_time
from collections import defaultdict

from prod_fs import ProD

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=100, n_features=20, n_classes=5, weights=[0.1, 0.2, 0.3, 0.25, 0.15], n_informative=5, random_state=0
)
y

array([1, 1, 4, 3, 0, 2, 2, 0, 4, 4, 3, 2, 3, 4, 1, 0, 1, 1, 1, 3, 2, 1,
       3, 2, 3, 2, 1, 4, 3, 2, 0, 3, 2, 1, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2,
       3, 1, 1, 2, 0, 1, 2, 2, 4, 2, 1, 1, 4, 4, 1, 2, 0, 2, 3, 1, 2, 1,
       1, 3, 2, 2, 2, 2, 0, 1, 2, 4, 1, 0, 4, 3, 2, 0, 3, 0, 4, 3, 3, 0,
       2, 3, 4, 2, 2, 4, 1, 2, 3, 4, 2, 3])

In [3]:
mapping = {0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e'}
y = np.array([mapping[y] for y in y])
y

array(['b', 'b', 'e', 'd', 'a', 'c', 'c', 'a', 'e', 'e', 'd', 'c', 'd',
       'e', 'b', 'a', 'b', 'b', 'b', 'd', 'c', 'b', 'd', 'c', 'd', 'c',
       'b', 'e', 'd', 'c', 'a', 'd', 'c', 'b', 'd', 'c', 'd', 'd', 'd',
       'c', 'c', 'd', 'd', 'c', 'd', 'b', 'b', 'c', 'a', 'b', 'c', 'c',
       'e', 'c', 'b', 'b', 'e', 'e', 'b', 'c', 'a', 'c', 'd', 'b', 'c',
       'b', 'b', 'd', 'c', 'c', 'c', 'c', 'a', 'b', 'c', 'e', 'b', 'a',
       'e', 'd', 'c', 'a', 'd', 'a', 'e', 'd', 'd', 'a', 'c', 'd', 'e',
       'c', 'c', 'e', 'b', 'c', 'd', 'e', 'c', 'd'], dtype='<U1')

In [4]:
ya = len([i for i in y if i == 'a'])
yb = len([i for i in y if i == 'b'])
yc = len([i for i in y if i == 'c'])
yd = len([i for i in y if i == 'd'])
ye = len([i for i in y if i == 'e'])
print(f"a: {ya}")
print(f"b: {yb}")
print(f"c: {yc}")
print(f"d: {yd}")
print(f"e: {ye}")

a: 11
b: 21
c: 30
d: 24
e: 14


In [5]:
# Proposed algorithm
tProD_start = process_time()
prodRankerWeighted = ProD(
    integration_method="trapz", delta=500, bw_method="scott",
    k=3, n_jobs=-1, mode="release", lower_end=-1.5, upper_end=2.5,
    averaging_method="weighted"
)
prodRankerWeighted.fit(X, y)
tProD_stop = process_time()
tProDWeighted = tProD_stop - tProD_start

Constructing and evaluating the KDEs per class for every feature ... 
 - Kernels constructed!
Computing intersection areas ...
 - averaging_method: 'weighted'


In [6]:
prodRankerWeighted.intersectionAreas

array([0.71145832, 0.63564732, 0.81711109, 0.70841378, 0.75649441,
       0.81497166, 0.81111009, 0.50231359, 0.73611806, 0.6656192 ,
       0.75198071, 0.6475677 , 0.37028615, 0.79426703, 0.88761998,
       0.66054676, 0.47699498, 0.68746631, 0.39470906, 0.7735549 ])

In [7]:
# Proposed algorithm
tProD_start = process_time()
prodRankerMean = ProD(
    integration_method="trapz", delta=500, bw_method="scott",
    k=3, n_jobs=-1, mode="release", lower_end=-1.5, upper_end=2.5,
    averaging_method="mean"
)
prodRankerMean.fit(X, y)
tProD_stop = process_time()
tProDMean = tProD_stop - tProD_start

Constructing and evaluating the KDEs per class for every feature ... 
 - Kernels constructed!
Computing intersection areas ...
 - averaging_method: 'mean'


In [8]:
prodRankerMean.intersectionAreas

array([0.7237607 , 0.66432447, 0.81666534, 0.69928661, 0.76432792,
       0.82158319, 0.80323319, 0.53176642, 0.72861477, 0.63945606,
       0.73314115, 0.66904253, 0.41712178, 0.80603756, 0.88791917,
       0.67524222, 0.48760547, 0.70605054, 0.42944544, 0.77521304])